export const VERIFY_EMAIL_REGISTER_SUCCESS = "VERIFY_EMAIL_REGISTER_SUCCESS";
export const VERIFY_EMAIL_REGISTER_ERROR = "VERIFY_EMAIL_REGISTER_ERROR";

export const CHANGE_EMAIL_REGISTER_SUCCESS = "CHANGE_EMAIL_REGISTER_SUCCESS";
export const CHANGE_EMAIL_REGISTER_ERROR = "CHANGE_EMAIL_REGISTER_ERROR";

export const VERIFY_USERNAME_REGISTER_SUCCESS = "VERIFY_USERNAME_REGISTER_SUCCESS";
export const VERIFY_USERNAME_REGISTER_ERROR = "VERIFY_USERNAME_REGISTER_ERROR";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const TRUNCATE_REGISTER = "TRUNCATE_REGISTER";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SET_AUTH_USER = "SET_AUTH_USER";

export const LOGOUT = "LOGOUT";
export const LOADING = "LOADING";